/*
 * catalog.h
 *
 *  Created on: 26 ????? 2018
 *      Author: stoledo
 */

#ifndef LOGGER_CATALOG_H_
#define LOGGER_CATALOG_H_

#define CATALOG_VERSION                           1

#define CATALOG_DATATYPE_SENSOR_CONFIG_FAILURE   49
#define CATALOG_DATATYPE_SENSOR_CONFIG           50

#define CATALOG_DATATYPE_SENSOR_BATMON_DATA      51
#define CATALOG_DATATYPE_SENSOR_BME280_DATA      52
#define CATALOG_DATATYPE_SENSOR_BMI160_DATA      53
#define CATALOG_DATATYPE_SENSOR_UBLOX_DATA       54
#define CATALOG_DATATYPE_SENSOR_BMP3XX_DATA      55

#define CATALOG_DATATYPE_TAG_ID                  80
#define CATALOG_DATATYPE_BLE_MAC_ADDRESS         81
#define CATALOG_DATATYPE_802_15_4_MAC_ADDRESS    82
#define CATALOG_DATATYPE_LVS_SUSPENSION          83
#define CATALOG_DATATYPE_TX_INVERSIONS           90
#define CATALOG_DATATYPE_VILDEHAYE_PACKET        70
#define CATALOG_DATATYPE_VILDEHAYE_CONFIG        71


#endif /* LOGGER_CATALOG_H_ */
